- Year, title, author, and DOI are used simply as identifiers for each paper. DOI is a permanent link, title gives a concise description of the work, and author and year provide valuable grouping and sorting criteria as well as identification.

- Scope, Goal, and Hypothesis give on overview of what the work attempts to show and why. Scope is concise, explaining the specific field in which the paper operates. Goal is more specific, giving a "to test", "to show", "to determine", etc. statement describing the papers aim. Hypothesis is the most specific, giving a testable prediction which we would like to adapt to the context of LLMs.

- Type, Design, Granularity, Treatment Count, and Treatments provide information that will largely be used in the recreation of experiments as these provide the blueprint for how the hypothesis was tested. Type describes the type of experiment such as case study or controlled experiment. Design describes whether the experiment uses a between or within subjects design, with all experiments in the set using the former to combat learning effects. Granularity broadly describes whether the experiment uses entire projects, or smaller user-stories/ requirements. Treatments and treatment count describe the number and nature of groups that an experiment is made up of.

- Cognitive Bias, Measurement, Effect size measurement, and Effect size magnitude provide information on what is being measured and why. Cognitive bias is the human mental shortcut that we are trying to observe/ recreate in the LLM. Measurement is the dependant variable(s) of the experiment, typically work effort (e.g. human hours). Effect size magnitude and measurement provide the qualitative and quantitative effect size where provided allowing for comparison and overview.

- Experiment count measures the number of distinct experiments in a paper allowing us to see where there are multiple findings of findings that build on each other. Participant profile, total participants, and participants per treatment allow us to see how many and what type of people took part in the study. Total participants and participants per treatment allow us to see at a glance if too few or uneven numbers of participants were used in experiments. Participant profile allows us to recreate the demographics with the LLMs or even to change them for generalisability. 

- Statistical tests can be used for comparison following LLM experiments or in the design of experiments where we see statistically insignificant results in the original paper, the column also acts as an initial reference though some tests may be inappropriate if we must change aspects of the experiment.

- Antipatterns, Essential, Desirable, and Extraordinary measure the strength of the original papers according to sigsoft's empirical standards. Antipatterns are common methodological problems that should be avoided such as inappropriate design which includes small sample sizes and uneven groups. Essential, Desirable, and Extraordinary are counts of the number of such attributes that are satisfied, there are 18 essential, 11 desirable, and four extraordinary attributes.
